const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:8000";

const USE_MOCK = import.meta.env.VITE_RAG_USE_MOCK === "true";

export async function searchBNHS(query, filter_type = null, accessToken = null) {
  if (USE_MOCK) {
    await new Promise((resolve) => setTimeout(resolve, 800));
    return {
      results: [
        {
          id: "mock-1",
          title: "Mock Vulture Report",
          summary: "This is a mock resource abstract.",
          content_type: "Species Field Accounts",
          source: "BNHS",
          image_url: "https://www.bnhs.org/public/img/logo-bird.png",
          bnhs_url: "https://www.bnhs.org/",
          similarity_score: 0.95
        },
      ],
    };
  }

  const cleanedQuery = query.trim();
  if (!cleanedQuery) throw new Error("Please enter a query.");

  const headers = { "Content-Type": "application/json" };
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`;

  const response = await fetch(`${API_BASE_URL}/api/search`, {
    method: "POST",
    headers,
    body: JSON.stringify({ query: cleanedQuery, limit: 10, filter_type }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.detail || `Request failed with status ${response.status}`);
  }
  return response.json();
}

export async function getNextSteps(current_resource, user_interests = [], accessToken = null) {
  if (USE_MOCK) {
    await new Promise((resolve) => setTimeout(resolve, 1500));
    return {
      actions: [
        { action_label: "Learn", description: "Read more about this", direct_link: "https://bnhs.org" },
        { action_label: "Explore", description: "Explore Virtual Museum", direct_link: "https://collections.bnhs.org" },
      ],
    };
  }

  const headers = { "Content-Type": "application/json" };
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`;

  const response = await fetch(`${API_BASE_URL}/api/next-steps`, {
    method: "POST",
    headers,
    body: JSON.stringify({ current_resource, user_interests }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.detail || `Request failed with status ${response.status}`);
  }
  return response.json();
}

export async function getQuiz(topic, num_questions = 5, accessToken = null) {
  if (USE_MOCK) {
    await new Promise((resolve) => setTimeout(resolve, 1500));
    return {
      questions: [
        {
          question: "Mock Question generated by LLM?",
          options: ["A", "B", "C", "D"],
          correct_answer: 0,
          explanation: "Because A is mock correct.",
          source_reference: "Mock BNHS Context",
        },
      ],
    };
  }

  const cleanedTopic = topic.trim();
  const headers = { "Content-Type": "application/json" };
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`;

  const response = await fetch(`${API_BASE_URL}/api/quiz`, {
    method: "POST",
    headers,
    body: JSON.stringify({ topic: cleanedTopic, num_questions }),
  });

  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(error.detail || `Request failed with status ${response.status}`);
  }
  return response.json();
}